In [1]:
import numpy as np

## Q2

In [21]:
i = np.array([[0.1, 0.1, 0.1],
              [0.1, 0.1, 0.9],
              [0.1, 0.9, 0.1],
              [0.1, 0.9, 0.9],
              [0.9, 0.1, 0.1],
              [0.9, 0.1, 0.9],
              [0.9, 0.9, 0.1],
              [0.9, 0.9, 0.9]])
o = np.array([[0.1, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9]]).transpose()

In [29]:
i_inverse = np.linalg.pinv(i)
w = np.dot(i_inverse, o)
np.round_(w,3)

array([[0.484],
       [0.484],
       [0.484]])

## Q3b

In [31]:
i = np.array([[0.1, 0.1],
              [0.1, 0.9],
              [0.9, 0.1],
              [0.9, 0.9]])
w1 = np.array([[-0.3, 0.1],
               [0.05, -0.17]])
w2 = np.array([[-0.7], [-0.2]])
ot = np.array([[0.1, 0.9, 0.9, 0.1]]).transpose()

In [42]:
h = np.dot(i, w1)
o = np.dot(h, w2)
e1 = ot - o
e1

array([[ 0.0811],
       [ 0.8819],
       [ 0.7291],
       [-0.0701]])

In [43]:
h

array([[-0.025, -0.007],
       [ 0.015, -0.143],
       [-0.265,  0.073],
       [-0.225, -0.063]])

In [45]:
e21 =  e1 / -0.7
e21

array([[-0.11585714],
       [-1.25985714],
       [-1.04157143],
       [ 0.10014286]])

In [46]:
-0.1/4

-0.025

In [48]:
e22 = e1 / -0.2
e22

array([[-0.4055],
       [-4.4095],
       [-3.6455],
       [ 0.3505]])

## Q4